#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := blink

SRCDIRS += ..\..\..\Users\gojimmypi\Documents\Arduino\hardware\espressif\esp32\cores\esp32 ..\..\..\Users\gojimmypi\Documents\Arduino\hardware\espressif\esp32\libraries\SPI ..\..\..\Users\gojimmypi\Documents\Arduino\hardware\espressif\esp32\variants\esp32
include $(IDF_PATH)/make/project.mk

